// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: fileformat.proto
// Protobuf Java Version: 4.30.2

package crosby.binary;

public final class Fileformat {
  private Fileformat() {
  }

  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 30,
      /* patch= */ 2,
      /* suffix= */ "",
      Fileformat.class.getName());
  }

  public static void registerAllExtensions(
    com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
    com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
      (com.google.protobuf.ExtensionRegistryLite) registry);
  }

  public interface BlobOrBuilder extends
    // @@protoc_insertion_point(interface_extends:OSMPBF.Blob)
    com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * When compressed, the uncompressed size
     * </pre>
     *
     * <code>optional int32 raw_size = 2;</code>
     *
     * @return Whether the rawSize field is set.
     */
    boolean hasRawSize();

    /**
     * <pre>
     * When compressed, the uncompressed size
     * </pre>
     *
     * <code>optional int32 raw_size = 2;</code>
     *
     * @return The rawSize.
     */
    int getRawSize();

    /**
     * <pre>
     * No compression
     * </pre>
     *
     * <code>bytes raw = 1;</code>
     *
     * @return Whether the raw field is set.
     */
    boolean hasRaw();

    /**
     * <pre>
     * No compression
     * </pre>
     *
     * <code>bytes raw = 1;</code>
     *
     * @return The raw.
     */
    com.google.protobuf.ByteString getRaw();

    /**
     * <pre>
     * Possible compressed versions of the data.
     * </pre>
     *
     * <code>bytes zlib_data = 3;</code>
     *
     * @return Whether the zlibData field is set.
     */
    boolean hasZlibData();

    /**
     * <pre>
     * Possible compressed versions of the data.
     * </pre>
     *
     * <code>bytes zlib_data = 3;</code>
     *
     * @return The zlibData.
     */
    com.google.protobuf.ByteString getZlibData();

    /**
     * <pre>
     * For LZMA compressed data (optional)
     * </pre>
     *
     * <code>bytes lzma_data = 4;</code>
     *
     * @return Whether the lzmaData field is set.
     */
    boolean hasLzmaData();

    /**
     * <pre>
     * For LZMA compressed data (optional)
     * </pre>
     *
     * <code>bytes lzma_data = 4;</code>
     *
     * @return The lzmaData.
     */
    com.google.protobuf.ByteString getLzmaData();

    /**
     * <pre>
     * Formerly used for bzip2 compressed data. Deprecated in 2010.
     * </pre>
     *
     * <code>bytes OBSOLETE_bzip2_data = 5 [deprecated = true];</code>
     *
     * @return Whether the oBSOLETEBzip2Data field is set.
     * @deprecated OSMPBF.Blob.OBSOLETE_bzip2_data is deprecated.
     * See fileformat.proto;l=47
     */
    @Deprecated
    boolean hasOBSOLETEBzip2Data();

    /**
     * <pre>
     * Formerly used for bzip2 compressed data. Deprecated in 2010.
     * </pre>
     *
     * <code>bytes OBSOLETE_bzip2_data = 5 [deprecated = true];</code>
     *
     * @return The oBSOLETEBzip2Data.
     * @deprecated OSMPBF.Blob.OBSOLETE_bzip2_data is deprecated.
     * See fileformat.proto;l=47
     */
    @Deprecated
    com.google.protobuf.ByteString getOBSOLETEBzip2Data();

    /**
     * <pre>
     * For LZ4 compressed data (optional)
     * </pre>
     *
     * <code>bytes lz4_data = 6;</code>
     *
     * @return Whether the lz4Data field is set.
     */
    boolean hasLz4Data();

    /**
     * <pre>
     * For LZ4 compressed data (optional)
     * </pre>
     *
     * <code>bytes lz4_data = 6;</code>
     *
     * @return The lz4Data.
     */
    com.google.protobuf.ByteString getLz4Data();

    /**
     * <pre>
     * For ZSTD compressed data (optional)
     * </pre>
     *
     * <code>bytes zstd_data = 7;</code>
     *
     * @return Whether the zstdData field is set.
     */
    boolean hasZstdData();

    /**
     * <pre>
     * For ZSTD compressed data (optional)
     * </pre>
     *
     * <code>bytes zstd_data = 7;</code>
     *
     * @return The zstdData.
     */
    com.google.protobuf.ByteString getZstdData();

    Blob.DataCase getDataCase();
  }

  /**
   * Protobuf type {@code OSMPBF.Blob}
   */
  public static final class Blob extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:OSMPBF.Blob)
    BlobOrBuilder {
    private static final long serialVersionUID = 0L;

    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 30,
        /* patch= */ 2,
        /* suffix= */ "",
        Blob.class.getName());
    }

    // Use Blob.newBuilder() to construct.
    private Blob(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }

    private Blob() {
    }

    public static final com.google.protobuf.Descriptors.Descriptor
    getDescriptor() {
      return Fileformat.internal_static_OSMPBF_Blob_descriptor;
    }

    @Override
    protected FieldAccessorTable
    internalGetFieldAccessorTable() {
      return Fileformat.internal_static_OSMPBF_Blob_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
          Blob.class, Builder.class);
    }

    private int bitField0_;
    private int dataCase_ = 0;
    @SuppressWarnings("serial")
    private Object data_;

    public enum DataCase
      implements com.google.protobuf.Internal.EnumLite,
      InternalOneOfEnum {
      RAW(1),
      ZLIB_DATA(3),
      LZMA_DATA(4),
      @Deprecated OBSOLETE_BZIP2_DATA(5),
      LZ4_DATA(6),
      ZSTD_DATA(7),
      DATA_NOT_SET(0);
      private final int value;

      private DataCase(int value) {
        this.value = value;
      }

      /**
       * @param value The number of the enum to look for.
       * @return The enum associated with the given number.
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @Deprecated
      public static DataCase valueOf(int value) {
        return forNumber(value);
      }

      public static DataCase forNumber(int value) {
        switch (value) {
          case 1:
            return RAW;
          case 3:
            return ZLIB_DATA;
          case 4:
            return LZMA_DATA;
          case 5:
            return OBSOLETE_BZIP2_DATA;
          case 6:
            return LZ4_DATA;
          case 7:
            return ZSTD_DATA;
          case 0:
            return DATA_NOT_SET;
          default:
            return null;
        }
      }

      public int getNumber() {
        return this.value;
      }
    }

    ;

    public DataCase
    getDataCase() {
      return DataCase.forNumber(
        dataCase_);
    }

    public static final int RAW_SIZE_FIELD_NUMBER = 2;
    private int rawSize_ = 0;

    /**
     * <pre>
     * When compressed, the uncompressed size
     * </pre>
     *
     * <code>optional int32 raw_size = 2;</code>
     *
     * @return Whether the rawSize field is set.
     */
    @Override
    public boolean hasRawSize() {
      return ((bitField0_ & 0x00000001) != 0);
    }

    /**
     * <pre>
     * When compressed, the uncompressed size
     * </pre>
     *
     * <code>optional int32 raw_size = 2;</code>
     *
     * @return The rawSize.
     */
    @Override
    public int getRawSize() {
      return rawSize_;
    }

    public static final int RAW_FIELD_NUMBER = 1;

    /**
     * <pre>
     * No compression
     * </pre>
     *
     * <code>bytes raw = 1;</code>
     *
     * @return Whether the raw field is set.
     */
    @Override
    public boolean hasRaw() {
      return dataCase_ == 1;
    }

    /**
     * <pre>
     * No compression
     * </pre>
     *
     * <code>bytes raw = 1;</code>
     *
     * @return The raw.
     */
    @Override
    public com.google.protobuf.ByteString getRaw() {
      if (dataCase_ == 1) {
        return (com.google.protobuf.ByteString) data_;
      }
      return com.google.protobuf.ByteString.EMPTY;
    }

    public static final int ZLIB_DATA_FIELD_NUMBER = 3;

    /**
     * <pre>
     * Possible compressed versions of the data.
     * </pre>
     *
     * <code>bytes zlib_data = 3;</code>
     *
     * @return Whether the zlibData field is set.
     */
    @Override
    public boolean hasZlibData() {
      return dataCase_ == 3;
    }

    /**
     * <pre>
     * Possible compressed versions of the data.
     * </pre>
     *
     * <code>bytes zlib_data = 3;</code>
     *
     * @return The zlibData.
     */
    @Override
    public com.google.protobuf.ByteString getZlibData() {
      if (dataCase_ == 3) {
        return (com.google.protobuf.ByteString) data_;
      }
      return com.google.protobuf.ByteString.EMPTY;
    }

    public static final int LZMA_DATA_FIELD_NUMBER = 4;

    /**
     * <pre>
     * For LZMA compressed data (optional)
     * </pre>
     *
     * <code>bytes lzma_data = 4;</code>
     *
     * @return Whether the lzmaData field is set.
     */
    @Override
    public boolean hasLzmaData() {
      return dataCase_ == 4;
    }

    /**
     * <pre>
     * For LZMA compressed data (optional)
     * </pre>
     *
     * <code>bytes lzma_data = 4;</code>
     *
     * @return The lzmaData.
     */
    @Override
    public com.google.protobuf.ByteString getLzmaData() {
      if (dataCase_ == 4) {
        return (com.google.protobuf.ByteString) data_;
      }
      return com.google.protobuf.ByteString.EMPTY;
    }

    public static final int OBSOLETE_BZIP2_DATA_FIELD_NUMBER = 5;

    /**
     * <pre>
     * Formerly used for bzip2 compressed data. Deprecated in 2010.
     * </pre>
     *
     * <code>bytes OBSOLETE_bzip2_data = 5 [deprecated = true];</code>
     *
     * @return Whether the oBSOLETEBzip2Data field is set.
     * @deprecated OSMPBF.Blob.OBSOLETE_bzip2_data is deprecated.
     * See fileformat.proto;l=47
     */
    @Override
    @Deprecated
    public boolean hasOBSOLETEBzip2Data() {
      return dataCase_ == 5;
    }

    /**
     * <pre>
     * Formerly used for bzip2 compressed data. Deprecated in 2010.
     * </pre>
     *
     * <code>bytes OBSOLETE_bzip2_data = 5 [deprecated = true];</code>
     *
     * @return The oBSOLETEBzip2Data.
     * @deprecated OSMPBF.Blob.OBSOLETE_bzip2_data is deprecated.
     * See fileformat.proto;l=47
     */
    @Override
    @Deprecated
    public com.google.protobuf.ByteString getOBSOLETEBzip2Data() {
      if (dataCase_ == 5) {
        return (com.google.protobuf.ByteString) data_;
      }
      return com.google.protobuf.ByteString.EMPTY;
    }

    public static final int LZ4_DATA_FIELD_NUMBER = 6;

    /**
     * <pre>
     * For LZ4 compressed data (optional)
     * </pre>
     *
     * <code>bytes lz4_data = 6;</code>
     *
     * @return Whether the lz4Data field is set.
     */
    @Override
    public boolean hasLz4Data() {
      return dataCase_ == 6;
    }

    /**
     * <pre>
     * For LZ4 compressed data (optional)
     * </pre>
     *
     * <code>bytes lz4_data = 6;</code>
     *
     * @return The lz4Data.
     */
    @Override
    public com.google.protobuf.ByteString getLz4Data() {
      if (dataCase_ == 6) {
        return (com.google.protobuf.ByteString) data_;
      }
      return com.google.protobuf.ByteString.EMPTY;
    }

    public static final int ZSTD_DATA_FIELD_NUMBER = 7;

    /**
     * <pre>
     * For ZSTD compressed data (optional)
     * </pre>
     *
     * <code>bytes zstd_data = 7;</code>
     *
     * @return Whether the zstdData field is set.
     */
    @Override
    public boolean hasZstdData() {
      return dataCase_ == 7;
    }

    /**
     * <pre>
     * For ZSTD compressed data (optional)
     * </pre>
     *
     * <code>bytes zstd_data = 7;</code>
     *
     * @return The zstdData.
     */
    @Override
    public com.google.protobuf.ByteString getZstdData() {
      if (dataCase_ == 7) {
        return (com.google.protobuf.ByteString) data_;
      }
      return com.google.protobuf.ByteString.EMPTY;
    }

    private byte memoizedIsInitialized = -1;

    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
      throws java.io.IOException {
      if (dataCase_ == 1) {
        output.writeBytes(
          1, (com.google.protobuf.ByteString) data_);
      }
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeInt32(2, rawSize_);
      }
      if (dataCase_ == 3) {
        output.writeBytes(
          3, (com.google.protobuf.ByteString) data_);
      }
      if (dataCase_ == 4) {
        output.writeBytes(
          4, (com.google.protobuf.ByteString) data_);
      }
      if (dataCase_ == 5) {
        output.writeBytes(
          5, (com.google.protobuf.ByteString) data_);
      }
      if (dataCase_ == 6) {
        output.writeBytes(
          6, (com.google.protobuf.ByteString) data_);
      }
      if (dataCase_ == 7) {
        output.writeBytes(
          7, (com.google.protobuf.ByteString) data_);
      }
      getUnknownFields().writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (dataCase_ == 1) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(
            1, (com.google.protobuf.ByteString) data_);
      }
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, rawSize_);
      }
      if (dataCase_ == 3) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(
            3, (com.google.protobuf.ByteString) data_);
      }
      if (dataCase_ == 4) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(
            4, (com.google.protobuf.ByteString) data_);
      }
      if (dataCase_ == 5) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(
            5, (com.google.protobuf.ByteString) data_);
      }
      if (dataCase_ == 6) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(
            6, (com.google.protobuf.ByteString) data_);
      }
      if (dataCase_ == 7) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(
            7, (com.google.protobuf.ByteString) data_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
        return true;
      }
      if (!(obj instanceof Blob)) {
        return super.equals(obj);
      }
      Blob other = (Blob) obj;

      if (hasRawSize() != other.hasRawSize()) return false;
      if (hasRawSize()) {
        if (getRawSize()
          != other.getRawSize()) return false;
      }
      if (!getDataCase().equals(other.getDataCase())) return false;
      switch (dataCase_) {
        case 1:
          if (!getRaw()
            .equals(other.getRaw())) return false;
          break;
        case 3:
          if (!getZlibData()
            .equals(other.getZlibData())) return false;
          break;
        case 4:
          if (!getLzmaData()
            .equals(other.getLzmaData())) return false;
          break;
        case 5:
          if (!getOBSOLETEBzip2Data()
            .equals(other.getOBSOLETEBzip2Data())) return false;
          break;
        case 6:
          if (!getLz4Data()
            .equals(other.getLz4Data())) return false;
          break;
        case 7:
          if (!getZstdData()
            .equals(other.getZstdData())) return false;
          break;
        case 0:
        default:
      }
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasRawSize()) {
        hash = (37 * hash) + RAW_SIZE_FIELD_NUMBER;
        hash = (53 * hash) + getRawSize();
      }
      switch (dataCase_) {
        case 1:
          hash = (37 * hash) + RAW_FIELD_NUMBER;
          hash = (53 * hash) + getRaw().hashCode();
          break;
        case 3:
          hash = (37 * hash) + ZLIB_DATA_FIELD_NUMBER;
          hash = (53 * hash) + getZlibData().hashCode();
          break;
        case 4:
          hash = (37 * hash) + LZMA_DATA_FIELD_NUMBER;
          hash = (53 * hash) + getLzmaData().hashCode();
          break;
        case 5:
          hash = (37 * hash) + OBSOLETE_BZIP2_DATA_FIELD_NUMBER;
          hash = (53 * hash) + getOBSOLETEBzip2Data().hashCode();
          break;
        case 6:
          hash = (37 * hash) + LZ4_DATA_FIELD_NUMBER;
          hash = (53 * hash) + getLz4Data().hashCode();
          break;
        case 7:
          hash = (37 * hash) + ZSTD_DATA_FIELD_NUMBER;
          hash = (53 * hash) + getZstdData().hashCode();
          break;
        case 0:
        default:
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static Blob parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }

    public static Blob parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }

    public static Blob parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }

    public static Blob parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }

    public static Blob parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }

    public static Blob parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }

    public static Blob parseFrom(java.io.InputStream input)
      throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
    }

    public static Blob parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static Blob parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
    }

    public static Blob parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }

    public static Blob parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
    }

    public static Blob parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() {
      return newBuilder();
    }

    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }

    public static Builder newBuilder(Blob prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
      BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }

    /**
     * Protobuf type {@code OSMPBF.Blob}
     */
    public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:OSMPBF.Blob)
      BlobOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
        return Fileformat.internal_static_OSMPBF_Blob_descriptor;
      }

      @Override
      protected FieldAccessorTable
      internalGetFieldAccessorTable() {
        return Fileformat.internal_static_OSMPBF_Blob_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
            Blob.class, Builder.class);
      }

      // Construct using crosby.binary.Fileformat.Blob.newBuilder()
      private Builder() {

      }

      private Builder(
        BuilderParent parent) {
        super(parent);

      }

      @Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        rawSize_ = 0;
        dataCase_ = 0;
        data_ = null;
        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
      getDescriptorForType() {
        return Fileformat.internal_static_OSMPBF_Blob_descriptor;
      }

      @Override
      public Blob getDefaultInstanceForType() {
        return Blob.getDefaultInstance();
      }

      @Override
      public Blob build() {
        Blob result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public Blob buildPartial() {
        Blob result = new Blob(this);
        if (bitField0_ != 0) {
          buildPartial0(result);
        }
        buildPartialOneofs(result);
        onBuilt();
        return result;
      }

      private void buildPartial0(Blob result) {
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.rawSize_ = rawSize_;
          to_bitField0_ |= 0x00000001;
        }
        result.bitField0_ |= to_bitField0_;
      }

      private void buildPartialOneofs(Blob result) {
        result.dataCase_ = dataCase_;
        result.data_ = this.data_;
      }

      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Blob) {
          return mergeFrom((Blob) other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Blob other) {
        if (other == Blob.getDefaultInstance()) return this;
        if (other.hasRawSize()) {
          setRawSize(other.getRawSize());
        }
        switch (other.getDataCase()) {
          case RAW: {
            setRaw(other.getRaw());
            break;
          }
          case ZLIB_DATA: {
            setZlibData(other.getZlibData());
            break;
          }
          case LZMA_DATA: {
            setLzmaData(other.getLzmaData());
            break;
          }
          case OBSOLETE_BZIP2_DATA: {
            setOBSOLETEBzip2Data(other.getOBSOLETEBzip2Data());
            break;
          }
          case LZ4_DATA: {
            setLz4Data(other.getLz4Data());
            break;
          }
          case ZSTD_DATA: {
            setZstdData(other.getZstdData());
            break;
          }
          case DATA_NOT_SET: {
            break;
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                data_ = input.readBytes();
                dataCase_ = 1;
                break;
              } // case 10
              case 16: {
                rawSize_ = input.readInt32();
                bitField0_ |= 0x00000001;
                break;
              } // case 16
              case 26: {
                data_ = input.readBytes();
                dataCase_ = 3;
                break;
              } // case 26
              case 34: {
                data_ = input.readBytes();
                dataCase_ = 4;
                break;
              } // case 34
              case 42: {
                data_ = input.readBytes();
                dataCase_ = 5;
                break;
              } // case 42
              case 50: {
                data_ = input.readBytes();
                dataCase_ = 6;
                break;
              } // case 50
              case 58: {
                data_ = input.readBytes();
                dataCase_ = 7;
                break;
              } // case 58
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }

      private int dataCase_ = 0;
      private Object data_;

      public DataCase
      getDataCase() {
        return DataCase.forNumber(
          dataCase_);
      }

      public Builder clearData() {
        dataCase_ = 0;
        data_ = null;
        onChanged();
        return this;
      }

      private int bitField0_;

      private int rawSize_;

      /**
       * <pre>
       * When compressed, the uncompressed size
       * </pre>
       *
       * <code>optional int32 raw_size = 2;</code>
       *
       * @return Whether the rawSize field is set.
       */
      @Override
      public boolean hasRawSize() {
        return ((bitField0_ & 0x00000001) != 0);
      }

      /**
       * <pre>
       * When compressed, the uncompressed size
       * </pre>
       *
       * <code>optional int32 raw_size = 2;</code>
       *
       * @return The rawSize.
       */
      @Override
      public int getRawSize() {
        return rawSize_;
      }

      /**
       * <pre>
       * When compressed, the uncompressed size
       * </pre>
       *
       * <code>optional int32 raw_size = 2;</code>
       *
       * @param value The rawSize to set.
       * @return This builder for chaining.
       */
      public Builder setRawSize(int value) {

        rawSize_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }

      /**
       * <pre>
       * When compressed, the uncompressed size
       * </pre>
       *
       * <code>optional int32 raw_size = 2;</code>
       *
       * @return This builder for chaining.
       */
      public Builder clearRawSize() {
        bitField0_ = (bitField0_ & ~0x00000001);
        rawSize_ = 0;
        onChanged();
        return this;
      }

      /**
       * <pre>
       * No compression
       * </pre>
       *
       * <code>bytes raw = 1;</code>
       *
       * @return Whether the raw field is set.
       */
      public boolean hasRaw() {
        return dataCase_ == 1;
      }

      /**
       * <pre>
       * No compression
       * </pre>
       *
       * <code>bytes raw = 1;</code>
       *
       * @return The raw.
       */
      public com.google.protobuf.ByteString getRaw() {
        if (dataCase_ == 1) {
          return (com.google.protobuf.ByteString) data_;
        }
        return com.google.protobuf.ByteString.EMPTY;
      }

      /**
       * <pre>
       * No compression
       * </pre>
       *
       * <code>bytes raw = 1;</code>
       *
       * @param value The raw to set.
       * @return This builder for chaining.
       */
      public Builder setRaw(com.google.protobuf.ByteString value) {
        if (value == null) {
          throw new NullPointerException();
        }
        dataCase_ = 1;
        data_ = value;
        onChanged();
        return this;
      }

      /**
       * <pre>
       * No compression
       * </pre>
       *
       * <code>bytes raw = 1;</code>
       *
       * @return This builder for chaining.
       */
      public Builder clearRaw() {
        if (dataCase_ == 1) {
          dataCase_ = 0;
          data_ = null;
          onChanged();
        }
        return this;
      }

      /**
       * <pre>
       * Possible compressed versions of the data.
       * </pre>
       *
       * <code>bytes zlib_data = 3;</code>
       *
       * @return Whether the zlibData field is set.
       */
      public boolean hasZlibData() {
        return dataCase_ == 3;
      }

      /**
       * <pre>
       * Possible compressed versions of the data.
       * </pre>
       *
       * <code>bytes zlib_data = 3;</code>
       *
       * @return The zlibData.
       */
      public com.google.protobuf.ByteString getZlibData() {
        if (dataCase_ == 3) {
          return (com.google.protobuf.ByteString) data_;
        }
        return com.google.protobuf.ByteString.EMPTY;
      }

      /**
       * <pre>
       * Possible compressed versions of the data.
       * </pre>
       *
       * <code>bytes zlib_data = 3;</code>
       *
       * @param value The zlibData to set.
       * @return This builder for chaining.
       */
      public Builder setZlibData(com.google.protobuf.ByteString value) {
        if (value == null) {
          throw new NullPointerException();
        }
        dataCase_ = 3;
        data_ = value;
        onChanged();
        return this;
      }

      /**
       * <pre>
       * Possible compressed versions of the data.
       * </pre>
       *
       * <code>bytes zlib_data = 3;</code>
       *
       * @return This builder for chaining.
       */
      public Builder clearZlibData() {
        if (dataCase_ == 3) {
          dataCase_ = 0;
          data_ = null;
          onChanged();
        }
        return this;
      }

      /**
       * <pre>
       * For LZMA compressed data (optional)
       * </pre>
       *
       * <code>bytes lzma_data = 4;</code>
       *
       * @return Whether the lzmaData field is set.
       */
      public boolean hasLzmaData() {
        return dataCase_ == 4;
      }

      /**
       * <pre>
       * For LZMA compressed data (optional)
       * </pre>
       *
       * <code>bytes lzma_data = 4;</code>
       *
       * @return The lzmaData.
       */
      public com.google.protobuf.ByteString getLzmaData() {
        if (dataCase_ == 4) {
          return (com.google.protobuf.ByteString) data_;
        }
        return com.google.protobuf.ByteString.EMPTY;
      }

      /**
       * <pre>
       * For LZMA compressed data (optional)
       * </pre>
       *
       * <code>bytes lzma_data = 4;</code>
       *
       * @param value The lzmaData to set.
       * @return This builder for chaining.
       */
      public Builder setLzmaData(com.google.protobuf.ByteString value) {
        if (value == null) {
          throw new NullPointerException();
        }
        dataCase_ = 4;
        data_ = value;
        onChanged();
        return this;
      }

      /**
       * <pre>
       * For LZMA compressed data (optional)
       * </pre>
       *
       * <code>bytes lzma_data = 4;</code>
       *
       * @return This builder for chaining.
       */
      public Builder clearLzmaData() {
        if (dataCase_ == 4) {
          dataCase_ = 0;
          data_ = null;
          onChanged();
        }
        return this;
      }

      /**
       * <pre>
       * Formerly used for bzip2 compressed data. Deprecated in 2010.
       * </pre>
       *
       * <code>bytes OBSOLETE_bzip2_data = 5 [deprecated = true];</code>
       *
       * @return Whether the oBSOLETEBzip2Data field is set.
       * @deprecated OSMPBF.Blob.OBSOLETE_bzip2_data is deprecated.
       * See fileformat.proto;l=47
       */
      @Deprecated
      public boolean hasOBSOLETEBzip2Data() {
        return dataCase_ == 5;
      }

      /**
       * <pre>
       * Formerly used for bzip2 compressed data. Deprecated in 2010.
       * </pre>
       *
       * <code>bytes OBSOLETE_bzip2_data = 5 [deprecated = true];</code>
       *
       * @return The oBSOLETEBzip2Data.
       * @deprecated OSMPBF.Blob.OBSOLETE_bzip2_data is deprecated.
       * See fileformat.proto;l=47
       */
      @Deprecated
      public com.google.protobuf.ByteString getOBSOLETEBzip2Data() {
        if (dataCase_ == 5) {
          return (com.google.protobuf.ByteString) data_;
        }
        return com.google.protobuf.ByteString.EMPTY;
      }

      /**
       * <pre>
       * Formerly used for bzip2 compressed data. Deprecated in 2010.
       * </pre>
       *
       * <code>bytes OBSOLETE_bzip2_data = 5 [deprecated = true];</code>
       *
       * @param value The oBSOLETEBzip2Data to set.
       * @return This builder for chaining.
       * @deprecated OSMPBF.Blob.OBSOLETE_bzip2_data is deprecated.
       * See fileformat.proto;l=47
       */
      @Deprecated
      public Builder setOBSOLETEBzip2Data(com.google.protobuf.ByteString value) {
        if (value == null) {
          throw new NullPointerException();
        }
        dataCase_ = 5;
        data_ = value;
        onChanged();
        return this;
      }

      /**
       * <pre>
       * Formerly used for bzip2 compressed data. Deprecated in 2010.
       * </pre>
       *
       * <code>bytes OBSOLETE_bzip2_data = 5 [deprecated = true];</code>
       *
       * @return This builder for chaining.
       * @deprecated OSMPBF.Blob.OBSOLETE_bzip2_data is deprecated.
       * See fileformat.proto;l=47
       */
      @Deprecated
      public Builder clearOBSOLETEBzip2Data() {
        if (dataCase_ == 5) {
          dataCase_ = 0;
          data_ = null;
          onChanged();
        }
        return this;
      }

      /**
       * <pre>
       * For LZ4 compressed data (optional)
       * </pre>
       *
       * <code>bytes lz4_data = 6;</code>
       *
       * @return Whether the lz4Data field is set.
       */
      public boolean hasLz4Data() {
        return dataCase_ == 6;
      }

      /**
       * <pre>
       * For LZ4 compressed data (optional)
       * </pre>
       *
       * <code>bytes lz4_data = 6;</code>
       *
       * @return The lz4Data.
       */
      public com.google.protobuf.ByteString getLz4Data() {
        if (dataCase_ == 6) {
          return (com.google.protobuf.ByteString) data_;
        }
        return com.google.protobuf.ByteString.EMPTY;
      }

      /**
       * <pre>
       * For LZ4 compressed data (optional)
       * </pre>
       *
       * <code>bytes lz4_data = 6;</code>
       *
       * @param value The lz4Data to set.
       * @return This builder for chaining.
       */
      public Builder setLz4Data(com.google.protobuf.ByteString value) {
        if (value == null) {
          throw new NullPointerException();
        }
        dataCase_ = 6;
        data_ = value;
        onChanged();
        return this;
      }

      /**
       * <pre>
       * For LZ4 compressed data (optional)
       * </pre>
       *
       * <code>bytes lz4_data = 6;</code>
       *
       * @return This builder for chaining.
       */
      public Builder clearLz4Data() {
        if (dataCase_ == 6) {
          dataCase_ = 0;
          data_ = null;
          onChanged();
        }
        return this;
      }

      /**
       * <pre>
       * For ZSTD compressed data (optional)
       * </pre>
       *
       * <code>bytes zstd_data = 7;</code>
       *
       * @return Whether the zstdData field is set.
       */
      public boolean hasZstdData() {
        return dataCase_ == 7;
      }

      /**
       * <pre>
       * For ZSTD compressed data (optional)
       * </pre>
       *
       * <code>bytes zstd_data = 7;</code>
       *
       * @return The zstdData.
       */
      public com.google.protobuf.ByteString getZstdData() {
        if (dataCase_ == 7) {
          return (com.google.protobuf.ByteString) data_;
        }
        return com.google.protobuf.ByteString.EMPTY;
      }

      /**
       * <pre>
       * For ZSTD compressed data (optional)
       * </pre>
       *
       * <code>bytes zstd_data = 7;</code>
       *
       * @param value The zstdData to set.
       * @return This builder for chaining.
       */
      public Builder setZstdData(com.google.protobuf.ByteString value) {
        if (value == null) {
          throw new NullPointerException();
        }
        dataCase_ = 7;
        data_ = value;
        onChanged();
        return this;
      }

      /**
       * <pre>
       * For ZSTD compressed data (optional)
       * </pre>
       *
       * <code>bytes zstd_data = 7;</code>
       *
       * @return This builder for chaining.
       */
      public Builder clearZstdData() {
        if (dataCase_ == 7) {
          dataCase_ = 0;
          data_ = null;
          onChanged();
        }
        return this;
      }

      // @@protoc_insertion_point(builder_scope:OSMPBF.Blob)
    }

    // @@protoc_insertion_point(class_scope:OSMPBF.Blob)
    private static final Blob DEFAULT_INSTANCE;

    static {
      DEFAULT_INSTANCE = new Blob();
    }

    public static Blob getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Blob>
      PARSER = new com.google.protobuf.AbstractParser<Blob>() {
      @Override
      public Blob parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<Blob> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<Blob> getParserForType() {
      return PARSER;
    }

    @Override
    public Blob getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface BlobHeaderOrBuilder extends
    // @@protoc_insertion_point(interface_extends:OSMPBF.BlobHeader)
    com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required string type = 1;</code>
     *
     * @return Whether the type field is set.
     */
    boolean hasType();

    /**
     * <code>required string type = 1;</code>
     *
     * @return The type.
     */
    String getType();

    /**
     * <code>required string type = 1;</code>
     *
     * @return The bytes for type.
     */
    com.google.protobuf.ByteString
    getTypeBytes();

    /**
     * <code>optional bytes indexdata = 2;</code>
     *
     * @return Whether the indexdata field is set.
     */
    boolean hasIndexdata();

    /**
     * <code>optional bytes indexdata = 2;</code>
     *
     * @return The indexdata.
     */
    com.google.protobuf.ByteString getIndexdata();

    /**
     * <code>required int32 datasize = 3;</code>
     *
     * @return Whether the datasize field is set.
     */
    boolean hasDatasize();

    /**
     * <code>required int32 datasize = 3;</code>
     *
     * @return The datasize.
     */
    int getDatasize();
  }

  /**
   * Protobuf type {@code OSMPBF.BlobHeader}
   */
  public static final class BlobHeader extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:OSMPBF.BlobHeader)
    BlobHeaderOrBuilder {
    private static final long serialVersionUID = 0L;

    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 30,
        /* patch= */ 2,
        /* suffix= */ "",
        BlobHeader.class.getName());
    }

    // Use BlobHeader.newBuilder() to construct.
    private BlobHeader(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }

    private BlobHeader() {
      type_ = "";
      indexdata_ = com.google.protobuf.ByteString.EMPTY;
    }

    public static final com.google.protobuf.Descriptors.Descriptor
    getDescriptor() {
      return Fileformat.internal_static_OSMPBF_BlobHeader_descriptor;
    }

    @Override
    protected FieldAccessorTable
    internalGetFieldAccessorTable() {
      return Fileformat.internal_static_OSMPBF_BlobHeader_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
          BlobHeader.class, Builder.class);
    }

    private int bitField0_;
    public static final int TYPE_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private volatile Object type_ = "";

    /**
     * <code>required string type = 1;</code>
     *
     * @return Whether the type field is set.
     */
    @Override
    public boolean hasType() {
      return ((bitField0_ & 0x00000001) != 0);
    }

    /**
     * <code>required string type = 1;</code>
     *
     * @return The type.
     */
    @Override
    public String getType() {
      Object ref = type_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs =
          (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          type_ = s;
        }
        return s;
      }
    }

    /**
     * <code>required string type = 1;</code>
     *
     * @return The bytes for type.
     */
    @Override
    public com.google.protobuf.ByteString
    getTypeBytes() {
      Object ref = type_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
          com.google.protobuf.ByteString.copyFromUtf8(
            (String) ref);
        type_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int INDEXDATA_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString indexdata_ = com.google.protobuf.ByteString.EMPTY;

    /**
     * <code>optional bytes indexdata = 2;</code>
     *
     * @return Whether the indexdata field is set.
     */
    @Override
    public boolean hasIndexdata() {
      return ((bitField0_ & 0x00000002) != 0);
    }

    /**
     * <code>optional bytes indexdata = 2;</code>
     *
     * @return The indexdata.
     */
    @Override
    public com.google.protobuf.ByteString getIndexdata() {
      return indexdata_;
    }

    public static final int DATASIZE_FIELD_NUMBER = 3;
    private int datasize_ = 0;

    /**
     * <code>required int32 datasize = 3;</code>
     *
     * @return Whether the datasize field is set.
     */
    @Override
    public boolean hasDatasize() {
      return ((bitField0_ & 0x00000004) != 0);
    }

    /**
     * <code>required int32 datasize = 3;</code>
     *
     * @return The datasize.
     */
    @Override
    public int getDatasize() {
      return datasize_;
    }

    private byte memoizedIsInitialized = -1;

    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasDatasize()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
      throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 1, type_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        output.writeBytes(2, indexdata_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        output.writeInt32(3, datasize_);
      }
      getUnknownFields().writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(1, type_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, indexdata_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, datasize_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
        return true;
      }
      if (!(obj instanceof BlobHeader)) {
        return super.equals(obj);
      }
      BlobHeader other = (BlobHeader) obj;

      if (hasType() != other.hasType()) return false;
      if (hasType()) {
        if (!getType()
          .equals(other.getType())) return false;
      }
      if (hasIndexdata() != other.hasIndexdata()) return false;
      if (hasIndexdata()) {
        if (!getIndexdata()
          .equals(other.getIndexdata())) return false;
      }
      if (hasDatasize() != other.hasDatasize()) return false;
      if (hasDatasize()) {
        if (getDatasize()
          != other.getDatasize()) return false;
      }
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasType()) {
        hash = (37 * hash) + TYPE_FIELD_NUMBER;
        hash = (53 * hash) + getType().hashCode();
      }
      if (hasIndexdata()) {
        hash = (37 * hash) + INDEXDATA_FIELD_NUMBER;
        hash = (53 * hash) + getIndexdata().hashCode();
      }
      if (hasDatasize()) {
        hash = (37 * hash) + DATASIZE_FIELD_NUMBER;
        hash = (53 * hash) + getDatasize();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static BlobHeader parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }

    public static BlobHeader parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }

    public static BlobHeader parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }

    public static BlobHeader parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }

    public static BlobHeader parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }

    public static BlobHeader parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }

    public static BlobHeader parseFrom(java.io.InputStream input)
      throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
    }

    public static BlobHeader parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static BlobHeader parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
    }

    public static BlobHeader parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }

    public static BlobHeader parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
    }

    public static BlobHeader parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() {
      return newBuilder();
    }

    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }

    public static Builder newBuilder(BlobHeader prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
      BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }

    /**
     * Protobuf type {@code OSMPBF.BlobHeader}
     */
    public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:OSMPBF.BlobHeader)
      BlobHeaderOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
        return Fileformat.internal_static_OSMPBF_BlobHeader_descriptor;
      }

      @Override
      protected FieldAccessorTable
      internalGetFieldAccessorTable() {
        return Fileformat.internal_static_OSMPBF_BlobHeader_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
            BlobHeader.class, Builder.class);
      }

      // Construct using crosby.binary.Fileformat.BlobHeader.newBuilder()
      private Builder() {

      }

      private Builder(
        BuilderParent parent) {
        super(parent);

      }

      @Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        type_ = "";
        indexdata_ = com.google.protobuf.ByteString.EMPTY;
        datasize_ = 0;
        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
      getDescriptorForType() {
        return Fileformat.internal_static_OSMPBF_BlobHeader_descriptor;
      }

      @Override
      public BlobHeader getDefaultInstanceForType() {
        return BlobHeader.getDefaultInstance();
      }

      @Override
      public BlobHeader build() {
        BlobHeader result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public BlobHeader buildPartial() {
        BlobHeader result = new BlobHeader(this);
        if (bitField0_ != 0) {
          buildPartial0(result);
        }
        onBuilt();
        return result;
      }

      private void buildPartial0(BlobHeader result) {
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.type_ = type_;
          to_bitField0_ |= 0x00000001;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.indexdata_ = indexdata_;
          to_bitField0_ |= 0x00000002;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.datasize_ = datasize_;
          to_bitField0_ |= 0x00000004;
        }
        result.bitField0_ |= to_bitField0_;
      }

      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof BlobHeader) {
          return mergeFrom((BlobHeader) other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(BlobHeader other) {
        if (other == BlobHeader.getDefaultInstance()) return this;
        if (other.hasType()) {
          type_ = other.type_;
          bitField0_ |= 0x00000001;
          onChanged();
        }
        if (other.hasIndexdata()) {
          setIndexdata(other.getIndexdata());
        }
        if (other.hasDatasize()) {
          setDatasize(other.getDatasize());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        if (!hasType()) {
          return false;
        }
        if (!hasDatasize()) {
          return false;
        }
        return true;
      }

      @Override
      public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                type_ = input.readBytes();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 18: {
                indexdata_ = input.readBytes();
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              case 24: {
                datasize_ = input.readInt32();
                bitField0_ |= 0x00000004;
                break;
              } // case 24
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }

      private int bitField0_;

      private Object type_ = "";

      /**
       * <code>required string type = 1;</code>
       *
       * @return Whether the type field is set.
       */
      public boolean hasType() {
        return ((bitField0_ & 0x00000001) != 0);
      }

      /**
       * <code>required string type = 1;</code>
       *
       * @return The type.
       */
      public String getType() {
        Object ref = type_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            type_ = s;
          }
          return s;
        } else {
          return (String) ref;
        }
      }

      /**
       * <code>required string type = 1;</code>
       *
       * @return The bytes for type.
       */
      public com.google.protobuf.ByteString
      getTypeBytes() {
        Object ref = type_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
          type_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      /**
       * <code>required string type = 1;</code>
       *
       * @param value The type to set.
       * @return This builder for chaining.
       */
      public Builder setType(
        String value) {
        if (value == null) {
          throw new NullPointerException();
        }
        type_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }

      /**
       * <code>required string type = 1;</code>
       *
       * @return This builder for chaining.
       */
      public Builder clearType() {
        type_ = getDefaultInstance().getType();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }

      /**
       * <code>required string type = 1;</code>
       *
       * @param value The bytes for type to set.
       * @return This builder for chaining.
       */
      public Builder setTypeBytes(
        com.google.protobuf.ByteString value) {
        if (value == null) {
          throw new NullPointerException();
        }
        type_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString indexdata_ = com.google.protobuf.ByteString.EMPTY;

      /**
       * <code>optional bytes indexdata = 2;</code>
       *
       * @return Whether the indexdata field is set.
       */
      @Override
      public boolean hasIndexdata() {
        return ((bitField0_ & 0x00000002) != 0);
      }

      /**
       * <code>optional bytes indexdata = 2;</code>
       *
       * @return The indexdata.
       */
      @Override
      public com.google.protobuf.ByteString getIndexdata() {
        return indexdata_;
      }

      /**
       * <code>optional bytes indexdata = 2;</code>
       *
       * @param value The indexdata to set.
       * @return This builder for chaining.
       */
      public Builder setIndexdata(com.google.protobuf.ByteString value) {
        if (value == null) {
          throw new NullPointerException();
        }
        indexdata_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }

      /**
       * <code>optional bytes indexdata = 2;</code>
       *
       * @return This builder for chaining.
       */
      public Builder clearIndexdata() {
        bitField0_ = (bitField0_ & ~0x00000002);
        indexdata_ = getDefaultInstance().getIndexdata();
        onChanged();
        return this;
      }

      private int datasize_;

      /**
       * <code>required int32 datasize = 3;</code>
       *
       * @return Whether the datasize field is set.
       */
      @Override
      public boolean hasDatasize() {
        return ((bitField0_ & 0x00000004) != 0);
      }

      /**
       * <code>required int32 datasize = 3;</code>
       *
       * @return The datasize.
       */
      @Override
      public int getDatasize() {
        return datasize_;
      }

      /**
       * <code>required int32 datasize = 3;</code>
       *
       * @param value The datasize to set.
       * @return This builder for chaining.
       */
      public Builder setDatasize(int value) {

        datasize_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }

      /**
       * <code>required int32 datasize = 3;</code>
       *
       * @return This builder for chaining.
       */
      public Builder clearDatasize() {
        bitField0_ = (bitField0_ & ~0x00000004);
        datasize_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:OSMPBF.BlobHeader)
    }

    // @@protoc_insertion_point(class_scope:OSMPBF.BlobHeader)
    private static final BlobHeader DEFAULT_INSTANCE;

    static {
      DEFAULT_INSTANCE = new BlobHeader();
    }

    public static BlobHeader getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<BlobHeader>
      PARSER = new com.google.protobuf.AbstractParser<BlobHeader>() {
      @Override
      public BlobHeader parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<BlobHeader> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<BlobHeader> getParserForType() {
      return PARSER;
    }

    @Override
    public BlobHeader getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_OSMPBF_Blob_descriptor;
  private static final
  com.google.protobuf.GeneratedMessage.FieldAccessorTable
    internal_static_OSMPBF_Blob_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_OSMPBF_BlobHeader_descriptor;
  private static final
  com.google.protobuf.GeneratedMessage.FieldAccessorTable
    internal_static_OSMPBF_BlobHeader_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
  getDescriptor() {
    return descriptor;
  }

  private static com.google.protobuf.Descriptors.FileDescriptor
    descriptor;

  static {
    String[] descriptorData = {
      "\n\020fileformat.proto\022\006OSMPBF\"\245\001\n\004Blob\022\020\n\010r" +
        "aw_size\030\002 \001(\005\022\r\n\003raw\030\001 \001(\014H\000\022\023\n\tzlib_dat" +
        "a\030\003 \001(\014H\000\022\023\n\tlzma_data\030\004 \001(\014H\000\022!\n\023OBSOLE" +
        "TE_bzip2_data\030\005 \001(\014B\002\030\001H\000\022\022\n\010lz4_data\030\006 " +
        "\001(\014H\000\022\023\n\tzstd_data\030\007 \001(\014H\000B\006\n\004data\"?\n\nBl" +
        "obHeader\022\014\n\004type\030\001 \002(\t\022\021\n\tindexdata\030\002 \001(" +
        "\014\022\020\n\010datasize\030\003 \002(\005B\017\n\rcrosby.binary"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[]{
        });
    internal_static_OSMPBF_Blob_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_OSMPBF_Blob_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
      internal_static_OSMPBF_Blob_descriptor,
      new String[]{"RawSize", "Raw", "ZlibData", "LzmaData", "OBSOLETEBzip2Data", "Lz4Data", "ZstdData", "Data",});
    internal_static_OSMPBF_BlobHeader_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_OSMPBF_BlobHeader_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
      internal_static_OSMPBF_BlobHeader_descriptor,
      new String[]{"Type", "Indexdata", "Datasize",});
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
